# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Down to Earth Dog Lady
email: erin@downtoearthdoglady.com
description: > # this means to ignore newlines until "baseurl:"
  The Down to Earth Dog Lady is a local Portland, Oregon dog trainer providing adventure pack hikes, walks, and dog training! Erin is a CPDT-KA , KPCTP certified dog trainer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://downtoearthdoglady.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile']
